#!/bin/bash
# Run the bot

# Work out BOT_HOME first (if needed)
[ -z $BOT_HOME ] && BOT_HOME=$(dirname $0) 

# Check for a bot environment
[ -e $BOT_HOME/.botenv ] && { 
    . ${BOT_HOME}/.botenv 
}

# Setup the environment
CLASSPATH="$BOT_HOME/src/main/groovy:$BOT_HOME/src/main/resources:$BOT_CLASSPATH:$BOT_HOME/bot-ext/src/main/groovy:$BOT_HOME/lib/*"
[ -d $BOT_HOME/bot-ext/scripts ] && {
    PATH="$BOT_HOME/bot-ext/scripts:$PATH"
}
export BOT_HOME CLASSPATH PATH

# Make sure we're groovy enough
which groovy > /dev/null || {
    # Check if we know where it lives
    [ -n "$GROOVY_HOME" ] && PATH="$PATH:${GROOVY_HOME}/bin" 
}

startbot=1
while [ $startbot -eq 1 ]; do
    # Start the bot
    groovy $JAVA_OPTS $BOT_HOME/src/main/groovy/bot.groovy $@
    
    # By default, we've had enough.
    startbot=0

    # Check if bot is just restarting
    [ -e ${BOT_HOME}/.restart ] && {
        startbot=1
        rm ${BOT_HOME}/.restart
    }

    continue
done

