#!/bin/bash
# Run gart

# Work out GART_HOME first (if needed)
[ -z $GART_HOME ] && GART_HOME=$(dirname $0) 

# Check for a gart environment
[ -e $GART_HOME/etc/gartenv ] && { 
    . ${GART_HOME}/etc/gartenv 
}

# Setup the environment
PATH="$GART_HOME:$GART_HOME/src/main/scripts:$PATH"
CLASSPATH="$GART_HOME/src/main/groovy:$GART_HOME/src/main/resources:$GART_CLASSPATH:$GART_HOME/lib/*"
JAVA_OPTS="$JAVA_OPTS 
-Djava.util.logging.config.file=${GART_HOME}/etc/logging.properties"
export GART_HOME CLASSPATH PATH JAVA_OPTS

# Set up the gart path
DEF_PATH="${GART_HOME}/src/main/groovy/gart:${GART_HOME}/src/main"
if [ -n "${GART_PATH}" ]
then
    GART_PATH="${GART_PATH}:${DEF_PATH}"
else
    GART_PATH="${DEF_PATH}"
fi
export GART_PATH

# Make sure we're groovy enough
which groovy > /dev/null || {
    # Check if we know where it lives
    [ -n "$GROOVY_HOME" ] && PATH="$PATH:${GROOVY_HOME}/bin" 
}

startgart=1
while [ $startgart -eq 1 ]; do
    # Start gart
    groovy $GART_HOME/src/main/groovy/gart.groovy $@
    
    # By default, we've had enough.
    startgart=0

    # Check if gart is just restarting
    [ -e ${GART_HOME}/.restart ] && {
        startgart=1
        rm ${GART_HOME}/.restart
    }

    continue
done

